eureka: 
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9004/eureka/
    instance:
      hostname: localhost
      prefer-ip-address: true
